### ISSUE TITLE
Issues / Questions / etc

### ISSUE THREAD

**Issue by morty** [datagovuk/ckanext-packagezip#1]
* Should everything in the zip file be contained in a directory so that when unzipped the contents doesn't just go straight into the pwd.
* Should we create our own datapackage or use a 3rd party tool?

**Comment by davidread** [comment]
Zip directory - I'm ambivalent. Why don't you see if there is any precedent in http://data.okfn.org/doc/data-package examples - I'm sure they are zipped.

datapackage.json - I think it is easy enough to create ourselves, without using a library
