### ISSUE TITLE
Include ea.sharefile.com links are pointless

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-packagezip#24]
We have some harvested datasets which point to sharefile.com as their resource. For example https://data.gov.uk/dataset/wfd-cycle-2-river-ph-classification/resource/5393dfc9-5177-45f6-99f6-a3e36c33af8f  points to https://ea.sharefile.com/share#/view/sb870abb351645ba9/fif263ad-4a3a-ac7c-39e8-9585c5ee1f20

That page on sharefile uses JS to serve the file, and the end results is that we serve the HTML in the datapackage (which has no format set).  We can't even work around sharefile by looking for it and working out the actual URL, as there isn't one.

Short of getting EA to stop using sharefile, maybe we should treat sharefile.com links as not being data?

**Comment by rossjones** [comment]
On my local (week old) db this is :

```
ckan=# select count(*) from resource where state='active' and url like '%ea.sharefile%';
 count
-------
   137
```

**Comment by davidread** [comment]
@morty is there someone at EA you can liaise with to understand why they are using sharefile and explain why this is problematic for DGU and its users to see if a better solution can be found?
