### ISSUE TITLE
HTML in packaagezip may cause confusion

### ISSUE THREAD

**Issue by rossjones** [datagovuk/ckanext-packagezip#25]
See https://twitter.com/environmentrisk/status/689904516435722240

This may be related to the issue in #24, or it may just be a misunderstanding of what the HTML is showing.  Maybe more text to clarify?

**Comment by davidread** [comment]
Whilst we should prod EA to see if they can avoid sharefile, I'm keen for
us to get the resource formats filled in, using Ross's script, and then zip
won't be offered.

The harvester has a number of extra fields which it doesn't overwrite (e.g.
theme), and we need to get it to also avoid overwriting the format too.

Dave

**Comment by davidread** [comment]
We decided to close this since now the packagezip has rerun (being a weekend), it is not offering the zip any more. Ideally it would decide this straight away, by ensuring QA runs before-hand, but that is a refinement we can get away without for the time being.
